steps:
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      - 'build'
      - '-f'
      - 'packages/autodiscovery/Dockerfile'
      - '-t'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/autodiscovery/autodiscovery:${_IMAGE_TAG}'
      - '/workspace'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/autodiscovery/autodiscovery:${_IMAGE_TAG}'

substitutions:
  _IMAGE_TAG: 'dev'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
