steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/example-legacy-project/autodiscovery-dataset-cleanup'
      - '-f'
      - 'scripts/Dockerfile'
      - '.'
images:
  - 'gcr.io/example-legacy-project/autodiscovery-dataset-cleanup'
