target-version = "py314"
line-length = 100

[lint]
select = ["D", "E", "F", "UP", "B", "SIM", "I", "W", "Q", "ASYNC", "T20"]

[lint.pydocstyle]
convention = "google"

[lint.per-file-ignores]
"**/tests/*.py" = ["D"]