import { Link, Typography } from '@mui/material';

import { BulletList, DialogBase } from '@/shared/DialogBase';

type DisclaimerDialogProps = {
    isOpen: boolean;
    onClose: () => void;
};

export const DisclaimerDialog = ({ isOpen, onClose }: DisclaimerDialogProps) => {
    return (
        <DialogBase isOpen={isOpen} onClose={onClose} title="Disclaimer">
            <Typography variant="body1" sx={{ mb: 2 }}>
                Asta supports scientific workflows by retrieving and synthesizing findings from the
                scholarly literature and, when provided, running exploratory analyses on user&apos;s
                uploaded datasets. As these are outputs generated by models, they have inherent
                limitations and may produce inaccurate, biased, or unexpected results. Any outputs
                from Asta are for informational purposes only and should not be relied upon for
                critical decision-making without independent verification. All features and models
                used in Asta are provided &quot;AS IS&quot; without any guarantees as to their
                accuracy, reliability, completeness, or quality.
            </Typography>
            <BulletList>
                <li>
                    <strong>Limits:</strong> Coverage of scholarly literature is incomplete and
                    excludes various paywalled or proprietary sources. Analyses depend on data
                    quality and inferred assumptions. Outputs can contain factual errors, omissions,
                    or misinterpretations.
                </li>
                <li>
                    <strong>Verification:</strong> Read the cited sources and review analysis steps,
                    code, and charts before drawing conclusions or taking action.
                </li>
                <li>
                    <strong>Appropriate use:</strong> Asta is not intended for non-scientific
                    queries or for professional advice (including medical, legal, or financial).
                </li>
            </BulletList>
            <Typography variant="body1" sx={{ mt: 1, mb: 2 }}>
                See our{' '}
                <Link
                    href="https://allenai.org/privacy-policy"
                    target="_blank"
                    rel="noopener noreferrer">
                    Privacy Policy
                </Link>
                ,{' '}
                <Link href="https://allenai.org/terms" target="_blank" rel="noopener noreferrer">
                    Terms of Use
                </Link>
                , and{' '}
                <Link
                    href="https://allenai.org/responsible-use"
                    target="_blank"
                    rel="noopener noreferrer">
                    Responsible Use
                </Link>{' '}
                for details.
            </Typography>
        </DialogBase>
    );
};
