name: Docker Compose Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: docker compose build
        env:
          # These all need to be set for the build.
          GOOGLE_APPLICATION_CREDENTIALS: /dev/null
          GCS_BUCKET: ""
          GCP_PROJECT: ""
          GOOGLE_ACCESS_KEY_ID: ""
          GOOGLE_ACCESS_KEY_SECRET: ""
